### ISSUE TITLE
download database manually

### ISSUE THREAD

**Issue by Thexiyang** [apcamargo/genomad#1]
Is it possible to download database manually instead of `genomad download-database`? Thanks!

**Comment by apcamargo** [comment]
Sure! Right now the link is https://portal.nersc.gov/genomad/__data__/genomad_db_v1.0.tar.gz

However I will release a new version really soon with a few additional markers and hallmark information for viral markers. With the `download-database` command you will always get the latest version of the database (as long as it is compatible with your version of geNomad).

**Comment by Thexiyang** [comment]
Does it mean I can directly use the db file after unzip? Thanks

**Comment by apcamargo** [comment]
Yes. The `download-database` basically checks the latest version of the database, downloads it, and them extracts. You can do that manually if you want.

**Comment by apcamargo** [comment]
I'll close this issue. Let me know if you got any other questions!

**Comment by jzrapp** [comment]
Hi @apcamargo! I would like to follow up on this: When I download the db manually and the run the end-to-end command, I get an error right away, because genomad_db/version.txt is missing. 
When I try to download via download-database it seems like the process is just stalling and nothing happens.

Could you help with that? Thanks so much!

**Comment by jzrapp** [comment]
Hi again, sorry, I think I realized what the issue was: I downloaded all 4 files from zenodo and kept them in a directory that I named genomad_db. Instead of pointing to the specific genomad_db_v1.1, I pointed to the directory with the 4 files. Sorry about that!

**Comment by apcamargo** [comment]
No problem :)
