### ISSUE TITLE
Optimization Request for Analyzing Large Number of MAGs with geNomad

### ISSUE THREAD

**Issue by Songfengl** [apcamargo/genomad#109]
First, I want to express my heartfelt gratitude for developing geNomad. This software has been incredibly helpful in identifying plasmids and viruses, significantly aiding research on horizontal gene transfer.

I am currently analyzing over 20,000 MAGs using geNomad. Using the default threads parameter (40 threads), I have noticed that it takes approximately 40 minutes to analyze a single MAG. Given the large number of MAGs, the overall time required for the analysis is substantial.

Could you please provide any suggestions or optimizations that could help expedite the analysis process? Are there any specific configurations, or other strategies that could reduce the computation time?

Thank you very much for your assistance and for creating such a valuable tool.

Best regards

**Comment by Songfengl** [comment]
I am considering merging all MAGs into a single contig set for analysis to potentially reduce the computational time. Could you please advise if this approach is feasible and whether it would affect the accuracy or performance of geNomad?

**Comment by apcamargo** [comment]
I'm glad that geNomad is helping you, @Songfengl!

I wouldn't merge all sequences into a single entry in the FASTA, as this would hurt both geNomad's performance and biological interpretation of the results. You can concatenate all MAGs into a single FASTA (with multiple entries, one per contig), and that will make things faster.

Other than that, you can disable the neural network module (`--disable-nn-classification`) or reduce the sensitivity of the marker search (e.g.: `-s 3`), but both options will hurt the classification performance.

**Comment by Songfengl** [comment]
Thank you so much for your quick response and valuable advice!

Just to clarify, does this mean I can use the cat command to concatenate all the FASTA files into a single file with multiple entries, one per contig? For example:

cat MAG1.fasta MAG2.fasta MAG3.fasta > combined_MAGs.fasta

Also, thank you for the suggestions on disabling the neural network module and adjusting the marker search sensitivity. I understand that these options might reduce classification performance.

Thanks again for your support and for developing such an impactful tool!

Best regards

**Comment by apcamargo** [comment]
Yep, that's what I mean :)

Let me know if you have any other questions! I'll close the issue for now

**Comment by Songfengl** [comment]
Thank you！！
