### ISSUE TITLE
Provirus detection in genomad vs checkv

### ISSUE THREAD

**Issue by lingrongjin** [apcamargo/genomad#112]
I used viral contigs identified through genomad pipeline as inputs for checkv for viral genome quality assessment. I noticed that checkv identified 870 proviruses whereas only 37 proviruses were predicted from genomad (and only 5 predictions were shared between the 2 tools). I'm a little surprised by this result as on CheckV's website, it says that checkv will not detect provirus if host regions have been removed (which I believe is what genomad does in the pipeline?). From my understanding, genomad is recommended as a more accurate tool for provirus detection. I'm wondering if I should treat the 870 provirus predicted by checkv just as "regular" viruses and trust the provirus result from genomad instead?

**Comment by apcamargo** [comment]
Hi @lingrongjin,

What was the input you gave to CheckV? For the contigs where geNomad detected a provirus, what did you feed to CheckV? The full contig or just the extracted provirus?

Note that CheckV isn't designed to find provirus from scratch in a sequence. It is meant to trim out the edges of viral sequences to remove genes that are possibly from the host.

Did you take a look at the genes that CheckV trimmed out?

**Comment by lingrongjin** [comment]
Hi Antonio,

I used the "virus.fna" output from genomad as the input for checkV. 

I'm not sure how to find the genes that CheckV trimmed out. Is this included in checkv output?

**Comment by apcamargo** [comment]
You can check the coordinates that were trimmed out in the CheckV summary file. From that you can take a look at a few genes to understand what is going on.

From experience, geNomad does a good job in not including the host genes in proviruses. Depending on your goals it might make sense to be more conservative (either with geNomad's parameters or by using CheckV), but you'll always risk losing a few vírus genes.

What was the total number of viruses in your input? If you want to make some sort of biological interpretation, this number (870) is probably an overestimate. For IMG/VR4 we used CheckV to trim out the edges only of the contigs that geNomad had identified as proviruses.
If you run `genomad find-proviruses -h` you can find some extra options that will give you more control over the provirus identification process. You can raise the minimum CRF score to make the identification more conservative, for example.

**Comment by lingrongjin** [comment]
Hi Antonio,

Thanks for your suggestions. I digged a little more into CheckV's descriptions and I think the result is making more sense to me now (please correct me if I'm wrong). So the two outputs by CheckV: viruses.fna and proviruses.fna represent viral sequences that are not trimmed and trimmed by CheckV, respectively. I have a total of 45438 viral sequences predicted by genomad, among which 870 were designated as "proviruses" by CheckV. Since CheckV is not specifically designed for predicting proviruses, these may just represent viral sequences that CheckV finds host regions/genes that it trims off. Does that sound like a reasonable interpretation of the result I got here? And like you said, whether we want to use CheckV's outputs or just use genomad as the final viral contigs for downstream analyses depend on whether we want to be more conservative or less but at risking of loosing a few viral genes.

**Comment by apcamargo** [comment]
Yes, CheckV will write trimmed sequences to `proviruses.fna` and non-trimmed sequences to `viruses.fna`. So, if it doesn't identify what it considers to be host genes in a provirus extracted by geNomad, the sequence will end up in `viruses.fna`.

> Does that sound like a reasonable interpretation of the result I got here? And like you said, whether we want to use CheckV's outputs or just use genomad as the final viral contigs for downstream analyses depend on whether we want to be more conservative or less but at risking of loosing a few viral genes.

Yes, it really depends on your goals. Like I said, for IMG/VR we trimmed only the sequences that geNomad had already predicted as proviruses, but if you are doing analysis for which you need to be extra-conservative (e.g. describing AMGs) its probably best to trim all sequences with CheckV.

**Comment by lingrongjin** [comment]
I agree, thanks for the detailed explanations!
