### ISSUE TITLE
question about integrase identification during provirus identification

### ISSUE THREAD

**Issue by mujiezhang** [apcamargo/genomad#115]
Hi，
geNomad is an excellent tools for identifing virus. I have read the paper carefully and have a question about provirus identification.
There are two types of virus encoded integrase, tyrosine integrase and serine integrase. But only tyrosine integrase was included in integrase identification according to your paper. So what is the reason for it?
![Snipaste_2024-08-02_10-35-44](https://github.com/user-attachments/assets/d113ce02-df09-422f-8c07-2e2507361887)

**Comment by apcamargo** [comment]
I evaluated serine integrases, but the accuracy of provirus boundary identification usually decreased when extending the boundary towards these integrases. This may have an underlying biological reason; serine integrases might not be as frequently present at the integration site as tyrosine integrases. However, I have not investigated this in depth.

**Comment by mujiezhang** [comment]
Thanks for your kindly reply!
