### ISSUE TITLE
cut-off point for plasmid_score

### ISSUE THREAD

**Issue by p-suazo-soto** [apcamargo/genomad#125]
Hello

I used genomad to search for resistance genes in metagenome plasmids from various environmental samples. The results were excellent, but I have a question. 
- First: Is there a cut-off point in the ‘plasmid_score’ in the summary results, to be sure that it is a plasmid that mobilises the resistance gene? Maybe a very high score like 0.9 is too strict?

- Second: I have different results in the plasmid score given by the ‘aggregated_classification’ plasmid_score versus the ‘plasmid_summary’ why does this happen? I ran genomad in a standard way. (001)

thanks

![001](https://github.com/user-attachments/assets/c97353c9-be63-44dd-a99d-1fa5ed466a1d)

**Comment by apcamargo** [comment]
Hi @p-suazo-soto

> First: Is there a cut-off point in the ‘plasmid_score’ in the summary results, to be sure that it is a plasmid that mobilises the resistance gene? Maybe a very high score like 0.9 is too strict?

geNomad already applies a 0.7 score cutoff ([you can read my answer to a previous question similar to yours](https://github.com/apcamargo/genomad/issues/118#issuecomment-2303810039). If you want to be more conservative I suggest requiring a hallmark gene (e.g., `--min-plasmid-hallmarks 1`).

Regarding mobilization: even though geNomad tells you which conjugation-related genes were identified, it does not applies rules upon those to categorize plasmids according to their mobility. I suggest you take the plasmids identified by geNomad and using them as inputs for a tool like [CONJscan](https://github.com/macsy-models/CONJScan).

> Second: I have different results in the plasmid score given by the ‘aggregated_classification’ plasmid_score versus the ‘plasmid_summary’ why does this happen? I ran genomad in a standard way. (001)

Did you use `--enable-score-calibration`? If not, the scores in the summary file and the scores file should be the same. Could you share the sequences and the output directory with me?

**Comment by p-suazo-soto** [comment]
Hello there,
Thanks for your reply. 
Don't use --enable-score-calibration-- that may be necessary to get the correct results. 
In the same sense, geNomad gives an output of resistance genes linked to whether they could be present in plasmids if the score is low for plasmids and high for chromosomes (>0.7).
Can I be sure that they are chromosomal?

Thank you for your prompt reply.
(when I have the data I will send them to you)

**Comment by apcamargo** [comment]
> Can I be sure that they are chromosomal?

They are most likely chromosomal, yes.

**Comment by apcamargo** [comment]
Thanks, @p-suazo-soto 

I just processed your data and I couldn't reproduce your issue. In my outputs, `k141_131787` has the same score in both the summary and scores files.

Maybe this was caused when you opened the file in Excel? Can you check that?

Plasmid summary:

```
seq_name      length   topology              n_genes   genetic_code   plasmid_score   fdr   n_hallmarks   marker_enrichment   conjugation_genes   amr_genes
-----------   ------   -------------------   -------   ------------   -------------   ---   -----------   -----------------   -----------------   -----------------
k141_131787   3243     No terminal repeats   4         11             0.8883          NA    0             0.1811              NA                  NA
```

Aggregated classification:

```
seq_name      chromosome_score   plasmid_score   virus_score
-----------   ----------------   -------------   -----------
k141_131787   0.0648             0.8883          0.0469
```

**Comment by p-suazo-soto** [comment]
That was the problem! I got the data crossed and misaligned.
Thank you for your time and sorry for this primitive error.

Thank you very much.

**Comment by apcamargo** [comment]
No worries!
