### ISSUE TITLE
sample-based assemblies vs merged?

### ISSUE THREAD

**Issue by mhmism** [apcamargo/genomad#128]
Hello,

Thank you or developing this very helpful tool. We are working on metagenomics samples, where we already performed sample based assemblies.

Now, I have two questions:
1- In our older pipelines, we used to aggregate all assemblies (i.e. concatenate them) in a single fasta file before down stream processing. So in that case, one fasta file will have thousands of different contigs coming from different samples, will be used as input to genomad. This is easier for us than running genomad on each separate sample assembly. Is this fine? and should we expect to a difference in performance? Note: we will use the score calibration option.
2- We are not interested in short contigs, let's say <2000 bp, or low quality fragments, therefore we will remove them beforehand before running genomad for faster processing time. Is this expected to affect genomad performance?

Thank you in advance!

**Comment by apcamargo** [comment]
Concatenating the FASTAs and removing short sequences shouldn't hurt performance. If anything, keeping only long sequences and having a lot of sequences in the input (due to the concatenation) will only improve the performance of calibration.

**Comment by mhmism** [comment]
Great to hear! Thanks for your prompt reply!

**Comment by apcamargo** [comment]
Let me know if you have any other questions!
