### ISSUE TITLE
Unable to install genomad on HPC

### ISSUE THREAD

**Issue by sadia-marjia** [apcamargo/genomad#129]
I am trying to install genome using the container . The .sif file is created successfully, but I am unable to download the database or find the genomad executable. 
This are the commands I am using,
apptainer pull docker://antoniopcamargo/genomad
apptainer exec --bind "$(pwd):/app" genomad_latest.sif download-database .
It gives error "FATAL:   "download-database": executable file not found in $PATH"

*Update* 
I was able to solve this by using,
apptainer run  --bind "$(pwd):/app" genomad_latest.sif download-database .

I also tried using conda, but it takes forever in solving the environment step and I had to quit every time. I could not find the what the issue is.

**Comment by apcamargo** [comment]
Good to hear that you solved the issue. This can serve as a reference for other people that have it.

Regarding Conda, the environment should be solved pretty quickly. Maybe you're using an old version (before they switched to the Mamba solver)? You can also try [Pixi](https://pixi.sh/latest/), which is even faster than Mamba.
