### ISSUE TITLE
provirus info appears in find_proviruses/provirus.tsv but lost in summary/summary.tsv

### ISSUE THREAD

**Issue by yumenghao2021** [apcamargo/genomad#13]
Hi, geNomad works well with most of my data overall. However, when I went in details checking if proviruses in find_provirus directory match exactly with all proviruses in summary directory, I got some mismatches. 

I guess some of thoes mismatches might come from post-classification filtering. Nevertheless, I also found some proviruses exist in summary part without cutting off bacterial squence as shown in find_provirus part. 
 
For example, in contig_find_proviruses/contig_provirus.tsv contig_1 was cut
seq_name        source_seq      start   end     length  n_genes v_vs_c_score    in_seq_edge     integrases
contig_1|provirus_5838_32914        contig_1|full    5838    32914   27077   41      24.1463 True    NA

On the contrary, in contig_summary/contig_summary.tsv, contig_1 was not cut
seq_name        length  topology        coordinates     n_genes genetic_code    virus_score     fdr     n_hallmarks     marker_enrichment       taxonomy
contig_1    32914   Linear  NA      48      11      0.9121  NA      1       14.5901 Viruses;Duplodnaviria;Heunggongvirae;Uroviricota;Caudoviricetes

This mismatch confused me a lot. Looking forward to the clarification. Thank you very much! 

Best, 
Menghao

**Comment by apcamargo** [comment]
Hi @yumenghao2021 

There are two reasons a putative provirus might not show up in the summary:
- As you mentioned, it might get discarded by the post-classification filtering process.
- If the full scaffold had a higher virus score than the putative provirus regions. I believe this is what happened in your example.

Can you check the scores of the provirus and the full contig, just to be sure? They will be in the `_aggregated_classification` directory.

**Comment by yumenghao2021** [comment]
Hi @apcamargo 
Thank you for the prompt reply! 
Yes, the score of the provirus contig is 0.9041, which is a little bit lower than that of the full contig (0.9121).

**Comment by apcamargo** [comment]
That's probably it then. In my testing, it is better to just keep the one with the higher score, but you can always take a look at it manually. :)

**Comment by yumenghao2021** [comment]
Will surely follow your consideration. Many thanks! :)
