### ISSUE TITLE
Processing many genomes

### ISSUE THREAD

**Issue by franciscozorrilla** [apcamargo/genomad#14]
Thanks for the tool, its been really easy to install and fast to run!
I was just wondering, if I have ~100 SAGs/MAGs to classify, would you suggest concatenating them into a single fasta file for processing in order to FDR corrrect across all genomes rather than on a per-genome-basis?

**Comment by apcamargo** [comment]
That's really nice to hear, @franciscozorrilla :)

It really depends on the total number of scaffolds. If it's [less than 1,000, calibration won't work well](https://portal.nersc.gov/genomad/_images/score_calibration_4.png) (in fact, you'd get a message saying that and it would not be used anyway). In any case, you can always concatenate and have a single run regarless of calibration, just to have a single output.
