### ISSUE TITLE
Difference between "Unclassified" and "Viruses" taxonomy?

### ISSUE THREAD

**Issue by ecampbell50** [apcamargo/genomad#19]
Thanks for making such a great tool! It's super easy to run and exactly what I need for my project.

Can you explain what the difference is between "Unclassified" and just "Viruses" in the taxonomy output? Does it mean that Unclassified hits are unknown if they're viruses at all? 

For example, I have 292 'Unclassified' hits and 7668 'Viruses' hits across 2000 genomes, does this mean the unclassified could have possibly been plasmid/chromosome?

**Comment by apcamargo** [comment]
Hi @ecampbell50. It's great to hear that geNomad has been useful for you!

Are you referring to the `taxonomy` column of the `_virus_summary.tsv` file? If so, all the sequences listed in that file were classified as viral. Sequences with an "Unclassified" value in that column were not be assigned to any virus taxon, but are likely viral regardless.

**Comment by ecampbell50** [comment]
Yes sorry I should've specified the file!
Thanks for clarifying the 'Unclassified' part. I was wondering what the "Viruses" classification also refers to? I have some hits showing just "Viruses" as a taxonomy:
<img width="1442" alt="Screenshot 2023-04-04 at 16 59 35" src="https://user-images.githubusercontent.com/109809676/229850078-622c2a23-7acc-4500-aa38-7b8b44e391a6.png">
(Apologies I should've put this in my first message)

**Comment by apcamargo** [comment]
No worries!

"Viruses" just mean that the genome could not be assigned to a specific realm. This can happen when, for instance, the genome was annotated by two markers with conflicting taxonomies, so there's no consensus realm.

**Comment by ecampbell50** [comment]
Perfect thank you so much! 😊

**Comment by apcamargo** [comment]
I'm happy to help! Let me know if you have any other questions :)

**Comment by apcamargo** [comment]
It's difficult to tell what is going on without further context. Are those sequences short? What is their CheckV quality? Have you tried to run geNomad with the `--relaxed` parameter?
