### ISSUE TITLE
Is it better to run geNomad on single genome assemblies?

### ISSUE THREAD

**Issue by joelwwh** [apcamargo/genomad#26]
I was wondering if there is a difference between

(1) Run geNomad 1000 times, one at a time per WGS assembly for 1000 genomes
or
(2) Run geNomad 1 time, by combine the 1000 WGS assemblies into a single fasta file 

**Is there a d ifference in how it works? Will the option (2) be treated like a 'metagenome' and hence run with different parameters? I have personally run (2) but am concerned if the accuracy is affected**

Also, if a contig is identified as virus (either prophage or non-integrated), will geNomad only take the part it thinks is viral or will it just give the whole contig? I have noticed that sometimes the 'coordinates' is NA and it simply just gave me the entire bacteria contig unchanged.

**Comment by apcamargo** [comment]
Option (2) would probably be faster, as long as your hardware can process that much data. Also, if you are using score calibration (`--enable-score-calibration`), you need a minimum of 1,000 per run. I recommend option (2).

If you have sequences with `NA` in the `coordinates` field of the `_virus_summary.tsv` file, it means that geNomad found viral sequences without host segments. It could be: (1) a non-integrated virus, (2) part of a provirus, without a host segment, (3) a provirus with a host segment that was not detected by geNomad.

Detected proviruses will have coordinates in the `coordinates` field and geNomad you provide you the sequence with the host regions removed.
