### ISSUE TITLE
nn classification stalls for large datasets

### ISSUE THREAD

**Issue by jzrapp** [apcamargo/genomad#3]
Hi again @apcamargo!

I've been able to successfully run genomad on several datasets (metagenomes). During the nn-classification I always receive an error in the log that says:

`2022-10-16 22:38:39.339717: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`

But the software keeps running and was able to finish successfully in some cases. However, for some very large datasets, the log shows this error and the software keeps running for >20h without any additional info on whether or not something is happening in the background. I cannot find a way to see what process is being executed. I left them running for now, still hoping that they will finish like the others, but it would be great if there was more info in the log on what is going on. 

Thanks!

**Comment by apcamargo** [comment]
Hi @jzrapp!

So, this error message just says that your hardware is not CUDA-compatible (which would make the neural network much faster). I'm not sure why your are getting the message, though. I've never saw it before. Can you provide your environment and hardware info?

As for the classification itself. geNomad classifies the data in batches to avoid overloading memory. You can try to increase the batch size using the `--batch-size` parameter (note that this parameter is only exposed if you run the `nn-classification` module separately). Let me know if you test this and find differences in classification speed.

That said, I used geNomad to classify tens of thousands of metagenomes/metatranscriptome (which included some pretty large assemblies) and the NN module never caused any issues (although it was the bottleneck for the really big assemblies).

If you don't want to test changing the batch size, you can always split the input FASTA and run multiple geNomad instances. Last case scenario, just skip the NN classification with `--disable-nn-classification`.

I'm aware that the NN module can be slow if the input is very large and I do have some plans to improve the situation, but right now I'm focusing on finishing the paper. It's definitely something that will improve in future releases :)

**Comment by apcamargo** [comment]
Thanks!

I'm still not sure what is causing the CUDA warning. I tried geNomad in a different server and got it. I'll investigate this.

In any case, the results were unaffected, so you don't need to worry about it :)

**Comment by apcamargo** [comment]
Hey @jzrapp, do you have any updates on this? Just wanted to be sure if I can close this bug and update the tutorial with additional recommendations for big datasets.

**Comment by jzrapp** [comment]
Hi @apcamargo, I'm sorry for my delayed response! I didn't get to it all of last week, and just restarted running those analyses. The easiest and quickest thing for me was to just split them up into 500MB chunks. Hopefully, this can do the trick for now. The other fasta files of around that size finished without issue. 
Sorry that I cannot provide a nicer workaround :/

**Comment by apcamargo** [comment]
No problem! I'll write a section in the tutorial with recommendations for very big datasets (disabling the nn classification, reducing the search sensitivity, etc.).

When I got the time, I'll update the NN module with a smaller model to make things faster. It is not a priority right now because it runs pretty quicky on the vast majority of the datasets. The might be an issue on how tensorflow is dealing with the datastream. I might investigate at which point this happens, since there's an abrupt slowdown at some point when datasets get bigger.

Let me know if you have updates on this! (or anything else)
