### ISSUE TITLE
Input file does not exist error

### ISSUE THREAD

**Issue by Elle-ctricity** [apcamargo/genomad#37]
Hello,

Thank you for making this. I am looking forward to using it. I have received the following error:

Invalid value for 'INPUT': Path 'sample_1.fa.gz' does not exist.

I have entered the correct path and also tried moving the file to my working directory with no avail. I am using singularity to run this in Docker, if that may pose any issues.

Thank you for your time

**Comment by apcamargo** [comment]
I don't have experience with Singularity, but it seems that you're not mounting the directory correctly. How are you running the command?

**Comment by Elle-ctricity** [comment]
Here is what I ran:
singularity run ./genomad_latest.sif
singularity run docker://genomad:latest end-to-end sample1.fa.gz output genomad_db

I could also try running locally with docker if all else fails

**Comment by apcamargo** [comment]
I just tested apptainer here and it worked as expected:

```
apptainer run $HOME/images/genomad.sif annotate test.fna genomad_output genomad_db
```

The only thing that didn't work is downloading the database. I'll try to figure out why.

In regards to your issue, do you have the same problem with other tools? It could be that your singularity is configured to not mount volumes automatically. Can you try to run with `--bind "$(pwd):/app"`?

**Comment by Elle-ctricity** [comment]
Thank you. I was able to get this working on docker, so it must be an issue with the singularity configuration
