### ISSUE TITLE
Error: prokka: Failed to download resource "aragorn"

### ISSUE THREAD

**Issue by AnnaaaaaaaaV** [apcamargo/genomad#41]
Hi everyone! 
I am new to this field and currently in the process of installing Prokka on my MacBook M2. Despite my attempts using both Homebrew and Conda package managers, the result is the same: Aragorn, a dependency of Prokka, is not available. I would greatly appreciate any assistance in resolving this matter !!

Error: prokka: Failed to download resource "aragorn"
Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.14\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.6\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head http://mbio-serv2.mbioekol.lu.se/ARAGORN/Downloads/aragorn1.2.38.tgz` exited with 56. Here's the output:
curl: (56) Recv failure: Connection reset by peer

**Comment by apcamargo** [comment]
Hi @AnnaaaaaaaaV 

The problem is that there's no pre-compiled binary of Aragorn in Conda for Apple processors. You can try to following the installation instructions here: https://github.com/apcamargo/genomad/issues/36#issuecomment-1739385550

**Comment by AnnaaaaaaaaV** [comment]
Thank you very much for your advice. Unfortunately, even when trying to use the commands you suggested, I didn't get any results. The response is: 

Could not solve for environment specs
The following package could not be installed
└─ prokka is not installable because it requires
   └─ aragorn >=1.2 , which does not exist (perhaps a missing channel).

**Comment by apcamargo** [comment]
What era the exact commands you are using?

**Comment by AnnaaaaaaaaV** [comment]
I’ve used the commands:

> conda install mamba -c conda-forge
> conda config --add channels conda-forge
conda config --add channels bioconda
> mamba install prokka

And I have obtained:

Looking for: ['prokka']
warning  libmamba Could not parse mod/etag header
bioconda/osx-arm64 (check zst)                      Checked  0.3s
warning  libmamba Could not parse mod/etag header
bioconda/noarch (check zst)                         Checked  0.2s
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
pkgs/main/osx-arm64 (check zst)                     Checked  0.2s
warning  libmamba Could not parse mod/etag header
pkgs/main/noarch (check zst)                       Checked  0.0s
warning  libmamba Could not parse mod/etag header
pkgs/r/osx-arm64 (check zst)                       Checked  0.0s
warning  libmamba Could not parse mod/etag header
pkgs/r/noarch (check zst)                          Checked  0.0s
bioconda/osx-arm64                                 124.0 B @   3.5kB/s  0.0s
pkgs/main/osx-arm64                                  1.7MB @  19.2MB/s  0.1s
pkgs/r/noarch                                        1.1MB @   8.5MB/s  0.0s
pkgs/main/noarch                                   697.2kB @   3.8MB/s  0.2s
pkgs/r/osx-arm64                                   108.0 B @ 500.0 B/s  0.1s
conda-forge/osx-arm64                                6.8MB @  24.0MB/s  0.3s
conda-forge/noarch                                  12.1MB @  35.6MB/s  0.3s
bioconda/noarch                                      4.7MB @   4.8MB/s  1.0s

Pinned packages:
  - python 3.11.*


Could not solve for environment specs
The following package could not be installed
└─ prokka is not installable because it requires
   └─ aragorn >=1.2 , which does not exist (perhaps a missing channel).


Previously, I have used both:
> brew install brewsci/bio/prokka
> conda install -c conda-forge -c bioconda -c defaults prokka

But the result was the same: Aragorn was not available.

Il giorno 7 ott 2023, alle ore 01:40, Antônio Camargo ***@***.***> ha scritto:



What era the exact commands you are using?

**Comment by apcamargo** [comment]
Can you try this:

```
mamba create -n prokka
mamba activate
conda config --env --set subdir osx-64
mamba install -c conda-forge -c bioconda prokka
mamba activate prokka
```

**Comment by AnnaaaaaaaaV** [comment]
Good morning!
Thank you so much for the commands! They worked 😃, and I was able to install Prokka!
Thank you very much for the support
A

Il giorno 7 ott 2023, alle ore 16:39, Antônio Camargo ***@***.***> ha scritto:



Can you try this:

mamba create -n prokka
mamba activate
conda config --env --set subdir osx-64
mamba install -c conda-forge -c bioconda prokka
mamba activate prokka

**Comment by apcamargo** [comment]
No worries :)

You might want to check out [Bakta](https://github.com/oschwengers/bakta). As far as I know, Prokka is not being maintained anymore
