### ISSUE TITLE
Fasta contains multiple entries with the same identifier

### ISSUE THREAD

**Issue by jsming1996** [apcamargo/genomad#44]
Hello, I got a error as " con1.fa is either empty or contains multiple entries with the same identifier. Please check your input FASTA file and execute genomad annotate again."
I noticed that genomad could used for metagenomic data in the website, however when I try to put this (con1.fa) as the input file, it doesn't work. In my mind, the identifier of every read could be repeat. Should I change all the identifiers?
could you provide a advice to solve this problem? I will really really appreciate about this. Best wishes!

**Comment by apcamargo** [comment]
Hi @jsming1996 

You can use [SeqKit](https://bioinf.shenwei.me/seqkit/usage/#rename) to solve that:

```bash
seqkit rename con1.fa > con1_no_duplicates.fa
```
