### ISSUE TITLE
Siphoviridae was not detected in metagenomic analysis

### ISSUE THREAD

**Issue by mijiandui** [apcamargo/genomad#5]
DearJamie Morton，

      Thanks a lot for your excellent software. However, we found  Siphoviridae was the majority one in the gut of previous studies. But we did not find it in our result with the software analysis. And we check the list ICTV VMR_19 and also did not found any more. Siphoviridae was removed? Could you please help me. Siphoviridae was combined to which order or family?
       Thanks a lot.
       Warm Regards
       Jiandui Mi

**Comment by apcamargo** [comment]
Hey @mijiandui,

Yeah, _Siphoviridae_ are not recognized anymore. This family was originally defined using morphological data, but this classification doesn't mirror viral evolution (see here: https://www.mdpi.com/1999-4915/13/3/506/htm).

Most tailed phages in metagenomes actually belong to non-described families, so it is pretty common to have sequences assigned to the class level (_Caudoviricetes_).
