### ISSUE TITLE
Marker classfication and other stuff

### ISSUE THREAD

**Issue by AhmedElsherbini** [apcamargo/genomad#57]
First, thanks for developing this great tool.
#############################################

With 1.72, this happens 

1. I tested a cohort of species, not with all files. but with ~20 % of genomes, I do struggle with marker classfications

```python
Traceback (most recent call last):
  File "/home/ahmed/anaconda3/envs/genomad/bin/genomad", line 10, in <module>
    sys.exit(cli())
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 1266, in end_to_end
    ctx.invoke(
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 656, in marker_classification
    genomad.marker_classification.main(
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/modules/marker_classification.py", line 503, in main
    ) = get_feature_array(
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/modules/marker_classification.py", line 247, in get_feature_array
    for annotated_contig in yield_annotated_contigs(
  File "/home/ahmed/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/modules/marker_classification.py", line 186, in yield_annotated_acontigs
    annotated_contigs_dict[contig].gene_rbs.append(rbs_categories_dict[rbs])
KeyError: 'AGTAGT'
```
######################################

2. Do you expect that the assembly method would affect the result of plasmid/provirus ? so if I have the same genome long vs hybrid vs short?
I have one sequence and it shows postive result for provirus in case of hybrid and in case of short read, zero.

######################################

3. For plasmid, in light of much more postive results in geNomad, I have totally different results (~zeros )in comparison to [plasmidfinder](https://cge.food.dtu.dk/services/PlasmidFinder/) and [PLSD](https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/search_form/seq/). 
In the later, I used the mash screen against my fasta files.
 
I see in the paper , you got your plasmids for ML training via PLSD. which makes me wondering. is it normal ?

for provirus, In relative to [phaster](http://phaster.ca/), However, geNomad seems abit more consertvative , just a  guess, may be PHASTER export the prophages whether complete or partial ? Over the fly, I think the results are comparable, I will update you regarding this with deeper look, if you are interested.

######################################
minor issue regarding installation:

4. for conda installation, I struggled to install in the HPC via conda. So, I made an python=3.9 env and installed it via pip along with other tools like aragon and mmseq2 (and worked when I installed them via conda ). For a normal Linux PC, it worked well if I used a conda normal environment. but if you try to install the environment via an extra path like 

```python
conda create -p genomad
```
did not not work.
######################################

Anyhowe, thanks again for your tool. I hope no bothering for you.

Best,
Ahmed

**Comment by apcamargo** [comment]
Hi @AhmedElsherbini 

> I tested a cohort of species, not with all files. but with ~20 % of genomes, I do struggle with marker classfications

This is a bug that was introduced recently and I'm still figuring out what is causing it. You can revert geNomad to version 1.7.0 to solve this.

> Do you expect that the assembly method would affect the result of plasmid/provirus ? so if I have the same genome long vs hybrid vs short? I have one sequence and it shows postive result for provirus in case of hybrid and in case of short read, zero.

Longer sequences will be more reliable. In this case, I'd expect that the hybrid assembly would be better.

> For plasmid, in light of much more postive results in geNomad, I have totally different results (~zeros )in comparison to [plasmidfinder](https://cge.food.dtu.dk/services/PlasmidFinder/) and [PLSD](https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/search_form/seq/). In the later, I used the mash screen against my fasta files. I see in the paper , you got your plasmids for ML training via PLSD. which makes me wondering. is it normal ?

It's difficult to say what is going on without taking a look at your sequences. Can you classify them with the `--relaxed` parameter and let me know what you get? By default, geNomad apply a couple of filters to try to reduce false positives, the `--relaxed` flag will disable those filters and more sequences will be classified as plasmids or viruses.

> for provirus, In relative to [phaster](http://phaster.ca/), However, geNomad seems abit more consertvative , just a guess, may be PHASTER export the prophages whether complete or partial ? Over the fly, I think the results are comparable, I will update you regarding this with deeper look, if you are interested.

Sure! Let me know what you find. If you want less conservative results, you can use the `--relaxed` flag, as stated above.

> for conda installation, I struggled to install in the HPC via conda. So, I made an python=3.9 env and installed it via pip along with other tools like aragon and mmseq2 (and worked when I installed them via conda ). For a normal Linux PC, it worked well if I used a conda normal environment. but if you try to install the environment via an extra path like

My guess is that this is because you didn't specify the channels. You need to have `-c conda-forge -c bioconda`.

**Comment by apcamargo** [comment]
> I apologize for not phrasing my question clearly. So, firstly my cohort is 97 genomes from two sister species. For plasmids, genomes have high estimation plasmids for some genomes like ~40 % of my cohort, and with an average 3 plasmids range (1 to 9). In comparison to PLSD and plasmidfinder which said the whole cohort has zero plasmids except one isolate with one plasmid.

My guess is that this is because PLSDB and plasmidfinder will compare your sequences to references. This will exclude new plasmids.

> I only had a quick idea to extract FASTA file from both PHASTER and geNomad. Using [clusterANI](https://github.com/moshi4/ANIclustermap), I exported the tree to use how far results are from each other. In this case, you can see that PHASTER has more results, which may be due to reporting both complete and non-complete provirus. If you have another idea to compare both outputs, it will be much appreciated. Beside using  relaxed model.

I suggest you run CheckV on these proviruses. Maybe these additional sequences are just small fragments (or not viruses at all).

> Also, I have observed that the tool command struggles with _. This means this command will not work until you remove _

I think that's because your `$f` variable is not isolated from `_`. Try this:

```bash
for d in *.fna ; do f=$(echo $d | sed -E "s/\.fna*//") ; genomad end-to-end --splits 8 --cleanup ${d}  ${f}_output ./genomad_db  ; done
```

**Comment by AhmedElsherbini** [comment]
Hi @apcamargo 

For plasmids, do you recommend any way to double-check these new plasmids?

For provirus, I used checkV. Indeed, in my two species, I can see that PHASTER may over-reports the medium and low quality and short fragments provirus, no wonder speaking of conservative mode. But interestingly for me, it does show fewer high-quality proviurs than geNomad. As you hinted before, may be PHASTER is similar to geNomad in relaxed mode.

![Rplot](https://github.com/apcamargo/genomad/assets/49863685/29442bd6-327b-4c79-9d79-f64e37d1399b)


Best,
Ahmed

**Comment by apcamargo** [comment]
There's no easy way to evaluate the predicted plasmids. Since you're working with isolates and I assume the assemblies are very contiguous, the results should be reliable. For fragmented assemblies it is often important to be a bit more conservative with the filters.

The large amount of NAs among PHASTER's predictions is a red flag. Be careful with those.

If you want to get more provirus predictions with geNomad, you could reduce the value of the `--marker-threshold` to 8. Keep in mind that this parameter is not exposed in the `end-to-end` command, thus you would have to run each module separately (as described [here](https://portal.nersc.gov/genomad/pipeline.html)). `--marker-threshold` is a parameter of the `find-proviruses` module.

**Comment by AhmedElsherbini** [comment]
Thank you very much for this,

For plasmids, I will report the **"potentiality"** of plasmids presnse in geNomad and mash screen of PLSD/plamsidfinder.

For provirus, I think I will focus only on hight quality phages with this default of geNomad. I think PHASTER is too much relaxed. 

Thank you for your time and effort.
