### ISSUE TITLE
Unable to download database v1.7.4

### ISSUE THREAD

**Issue by SCWang429** [apcamargo/genomad#67]
Hello, I am new to genomad and tried to download database through `genomad download-database .` with version v1.7.4. But I got the error: 

```
[19:16:41] Requesting https://portal.nersc.gov/genomad/__data__/genomad_db_v1.7.tar.gz.
.....
urllib.error.HTTPError: HTTP Error 404: Not Found
```

I checked https://portal.nersc.gov/genomad/__data__/ and found there is no genomad_db_v1.7.tar.gz file. Will it be fixed or shall I download v1.6 database?

Thank you!

**Comment by apcamargo** [comment]
Sorry, I was updating the database. You should be able to download it now :)

**Comment by SCWang429** [comment]
Thanks for your quick reply. It works now 🙂

**Comment by apcamargo** [comment]
Good to hear! I'll close this issue then
