### ISSUE TITLE
How to further develop on the basis of your code 

### ISSUE THREAD

**Issue by zzzfire** [apcamargo/genomad#68]
Hello, 
I recently discovered your genomad on GitHub, and I am deeply impressed by it. This tool has provided me with insights and inspirations. 
I would like to perform secondary development on your program. I hope you could guide me on how to further develop on the basis of your code and the corresponding steps for this secondary development.
I know this may be presumptuous, but I sincerely hope to get your help.

**Comment by apcamargo** [comment]
Hi @zzzfire 

I'm glad you enjoyed using geNomad! It's great that you are interested in collaborating with code!

I don't have a guide on how to contribute, so my suggestion is to first take a look at the code from the main modules to understand how it works (which outputs each module produces, how are modules connected to each other, etc.). Then, if you want to start contributing, you could start with this: https://github.com/apcamargo/genomad/issues/48

Another, more complicated issue, that you could try to work on is this one: https://github.com/apcamargo/genomad/issues/46

Let me know if you have any questions!

**Comment by zzzfire** [comment]
Hello,
I noticed that your program was finally packaged into a genomad package. I would like to ask, if I make changes to the code within it, how should I call the modified program?

**Comment by apcamargo** [comment]
You can install it with flit:

```
flit install -s
```
