### ISSUE TITLE
Could you please explain the functions of these files？

### ISSUE THREAD

**Issue by a-piece-of-teemo** [apcamargo/genomad#69]
Hello author, 
while reviewing your code, I'm not clear about the purpose of these files. Could you please explain their functions?

![image](https://github.com/apcamargo/genomad/assets/113283540/69e89f20-5314-41bb-8424-d1055c5f5b18)

**Comment by apcamargo** [comment]
Most of those just carry the model weights.

- `decision_forest.ubj`: Decision forest model used for the marker-based classification.
- `nn_classifier.h5`: Neural network used for the sequence-based classification.
- `provirus_tagget.crfsuite`: Conditional random field model used for provirus identification.
- `rbs_categories.tsv`: Tabular file grouping the RBS motifs identified by prodigal-gv into a few groups.
- `score_calibration_weights.nps`: Binary file containing the weights of the score calibration model.
- `score_calibration_weights.py`: Text file containing the weights of the score calibration model.
