### ISSUE TITLE
Several questions about geNomad

### ISSUE THREAD

**Issue by xjhzjucas** [apcamargo/genomad#74]
Dear developer: Thank you for developing this nice tool! I want to ask some basic questions about it:
1.Can we consider the sequences belong to 'proviruses' as 'temperate virus' and the left sequence as 'lytic virus'? Can it used for lifestyle prediction?
2. If we use the assemble results like contigs as input, can we think that geNomad serve as the similar role as Virsorter that it distinguishes viral sequences and host sequences? I am entangled with which input files would be better:①vOTU sequences(from former steps of viral contigs identification and vOTU clustering);②contigs sequences(from assembling the metagenomes,i.e. I want to let geNomad help me to distinguish viral contigs instead of Virsorter)

Could you help me figure out these problems? I'm sorry to ask such basic questions because I am really a beginner in this field. Thank you so much！

**Comment by apcamargo** [comment]
Hi @xjhzjucas


1. You can consider proviruses as likely temperate, but I wouldn't consider the rest as lytic. They might be temperate viruses that were sequenced in a non-integrated form or fragments of temperate viruses without flanking host sequences.
2. geNomad will do virus identification for you, so (2) is the better option. You check the virus classification performance on [Figure 3 of the manuscript](https://www.nature.com/articles/s41587-023-01953-y).

**Comment by xjhzjucas** [comment]
> Hi @xjhzjucas
> 
> 1. You can consider proviruses as likely temperate, but I wouldn't consider the rest as lytic. They might be temperate viruses that were sequenced in a non-integrated form or fragments of temperate viruses without flanking host sequences.
> 2. geNomad will do virus identification for you, so (2) is the better option. You check the virus classification performance on [Figure 3 of the manuscript](https://www.nature.com/articles/s41587-023-01953-y).

Hi @apcamargo 
Thank you for your help, this is really helpful for me and solves my doubts!
