### ISSUE TITLE
genomad hangs

### ISSUE THREAD

**Issue by erinyoung** [apcamargo/genomad#80]
Hi! I have a strange use case.

I'm trying to run genomad in gitpod - which has very low computational options. 

I get to this step where it hangs:

```
 => => # [20:51:22] Proteins predicted with pyrodigal-gv were written to                                                                                      
 => => #            GCA_025259185.1_ASM2525918v1_genomic_proteins.faa.
 ```
 Is there anything I can do to get it to... not hang?

**Comment by apcamargo** [comment]
Hi @erinyoung 

If MMseqs2 is hanging, you can try to increase the number of splits (e.g. `-s 16`). 

Other than that, you can take a look at some tips here: https://portal.nersc.gov/genomad/faq.html

**Comment by erinyoung** [comment]
Perfect! Thank you!
