### ISSUE TITLE
Recommendation for taxonomic classification of ssDNA virus

### ISSUE THREAD

**Issue by ChenTianYi99** [apcamargo/genomad#85]
Hi,
i have used several virus identification tools to obtain a viral sequence set and applied CheckV for further validation. In following analyses, i just want to focus on ssDNA viruses. So are there any recommended parameters of genoMad for taxonomic classification of ssDNA viruses (should be more conservative)?

Looking forward to your reply. Thanks in advance.

**Comment by apcamargo** [comment]
If you already included geNomad for the identification, you can just get the assigned taxonomy from the `{prefix}_annotate/{prefix}_taxonomy.tsv` file. If not, you can just run `genomad annotate` to generate this file.

My only suggestion is to, if possible, increase the sensitivity of the marker search to try to increase the fraction of genomes with taxonomic assignment. You can do this via the `-s` parameter (e.g.: `-s 7.2`). Please note that increasing the search sensitivity will increase the memory usage.

**Comment by ChenTianYi99** [comment]
Thanks for your rapid reply. Besides the sensitivity parameter, should i increase the minimum number of virus hallmarks in my virus set?

**Comment by apcamargo** [comment]
If you're confident that those sequences are viruses, I don't think that's necessary. The number of hallmarks is important for classification, but they don't really improve taxonomic assignment.

**Comment by ChenTianYi99** [comment]
Thank you very much. It really helps a lot.

**Comment by apcamargo** [comment]
No problem!
