### ISSUE TITLE
Can we input virus(phage) sequences to identify the plasmid sequence in the virus sequence?

### ISSUE THREAD

**Issue by Caiyulu-818** [apcamargo/genomad#86]
Hi,
can we input virus(phage) sequences to identify the plasmid sequence in the virus sequence? 

From this result, can we assume that the recognized plasmid sequence is phage-plasmid?

**Comment by apcamargo** [comment]
Most phage-plasmids will be classified as virus by geNomad. What you can do is identify the sequences that have multiple `PP`, `PV`, or `VP` markers (you can read about these types of markers [here](https://portal.nersc.gov/genomad/marker_features.html#genomad-s-marker-dataset)). These markers are found in plasmids and can help you identifying phage-plasmids in a dataset.

**Comment by Caiyulu-818** [comment]
Thank you very much for your reply! I will adopt your suggestion to find the specific plasmid markers~
---- Replied Message ----
FromAntônio ***@***.***>Date04/02/2024 00:38 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [apcamargo/genomad] Can we input virus(phage) sequences to identify the plasmid sequence in the virus sequence? (Issue #86)
Most phage-plasmids will be classified as virus by geNomad. What you can do is identify the sequences that have multiple PP, PV, or VP markers (you can read about these types of markers here). These markers are found in plasmids and can help you identifying phage-plasmids in a dataset.

**Comment by apcamargo** [comment]
Let me know what you find!

**Comment by Caiyulu-818** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi, apcamargoYes,  I input the virus sequence, which I found in the plasmid summary file, some sequences were identified as plasmid with plasmid score >0.7( default mode),see attachment 1. Besides, I found there are multiply PP PV or PC markers in the plasmid gene summary (see attachment 2), whether these results can ensure these plasmids identified in the virus sequences are phage-plasmid?  Best regardsLucy
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                lucyncs123
                                    Zhejiang University
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Antônio ***@***.***>
            
        
      
      
        
         Date 
        
        
        04/2/2024 00:38
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [apcamargo/genomad] Can we input virus(phage) sequences to identify the plasmid sequence in the virus sequence? (Issue #86)
        
      
    
  
  
Most phage-plasmids will be classified as virus by geNomad. What you can do is identify the sequences that have multiple PP, PV, or VP markers (you can read about these types of markers here). These markers are found in plasmids and can help you identifying phage-plasmids in a dataset.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by apcamargo** [comment]
Right now, there's no "standard" computational method to identify phage-plasmids. They are pretty much [any element that share genes with both viruses and plasmids](https://academic.oup.com/nar/article/49/5/2655/6137301), so there's no rule of thumb. You can take a look at the distribution of PV/PP/VP markers in your data to evaluate a good cutoff.
