### ISSUE TITLE
Circular virus identification

### ISSUE THREAD

**Issue by xjhzjucas** [apcamargo/genomad#92]
Hi developer, I'm curious about can genomad identify circular virus and how?
Can I use the checkv trimmed sequence as input of geNomad? If so, would this affect the result of circular virus identification?
Thank you so much!

**Comment by xjhzjucas** [comment]
Thank you for your help!
I'm sorry let me explain why I ask such a question, because I don't know how to use CheckV to identify circular virus so then I want to use genoamd instead to identify circular virus. In the result of checkv, I didn't find the information of circular virus and don't know what informations refer to.

**Comment by apcamargo** [comment]
In the summary file, just find the sequences with `DTR` in the `topology` column.

**Comment by xjhzjucas** [comment]
Thank you for your help!

**Comment by apcamargo** [comment]
No problem!
