### ISSUE TITLE
Whether measures have been taken by genomad to avoid identifying genomic islands as viruses?

### ISSUE THREAD

**Issue by ZongzhiWu** [apcamargo/genomad#96]
Dear authors,

I wonder if any measures have been taken by genomad to avoid identifying genomic islands as viruses?

Thanks a lot!

**Comment by apcamargo** [comment]
Yes, geNomad shouldn't classify genomic islands as proviruses. The default cutoffs will remove those for you. If you want to be extra conservative, you may require proviruses to have a virus hallmark

**Comment by ZongzhiWu** [comment]
Will genomic islands be classified as plasmids or chromosomes in genomad?

**Comment by apcamargo** [comment]
This shouldn't happen. However, ICEs and plasmids can be very similar, so if your assembly is very fragmented and the chromosome regions flanking ICEs are absent, it is possible that they will be classified as plasmids

**Comment by apcamargo** [comment]
This shouldn't happen. However, ICEs and plasmids can be very similar, so if your assembly is very fragmented and the chromosome regions flanking ICEs are absent, it is possible that they will be classified as plasmids

**Comment by ZongzhiWu** [comment]
Thank you very much for your reply.
